pop-os/cosmic-session

- src/comp.rs
- src/generic.rs
- src/main.rs
- src/process.rs
This may still leak fds in some error cases. That can be solved by using `OwnedFd` when the next Rust stable releases.
> Don't leak fds, and don't unset cloexec except/until needed

- data/start-cosmic
This will source the user's `~/.profile` if it exists and is executable.
> Source user profile

- Cargo.lock
- Cargo.toml
- src/comp.rs
- src/main.rs
It is better to have `cosmic-comp` and `cosmic-panel` log to journald themselves.
Having panics logged should be helpful if panics ever occur.
See https://github.com/pop-os/cosmic-comp/pull/60 and https://github.com/pop-os/cosmic-panel/pull/20.
Though it is useful for us to log when the subprocess terminates with and exit status or signal. https://github.com/pop-os/launch-pad/pull/3 handles this.
> Don't log output of cosmic-comp/cosmic-panel, log panics

- data/start-cosmic
Untested, but this should allow the usage of Xwayland by QT, e.g. if the wayland-plugin is simply not installed or not available for some other reason, while still preferring wayland.
> Allow xcb QT_QPA_PLATFORM as a fallback

- data/start-cosmic
- extract out systemd-specific changes from https://github.com/pop-os/cosmic-session/pull/31
- this checks for `systemctl` before calling it, which should make systemd optional for this script
> fix: check before using `systemctl`

- data/start-cosmic
- fixes #23 
- inspired by long-established behaviour in GNOME (GPL-2): https://gitlab.gnome.org/GNOME/gnome-session/-/blob/998ed1d8ee2ff5396583c284230648625b4103e5/gnome-session/gnome-session.in#L10
- tested with a new user account with SHELL=/usr/bin/bash
- tested with existing user account with SHELL=/usr/bin/nu
> fix: use preferred SHELL in login shell mode

- src/main.rs
- src/systemd.rs
- extracted out common `std::process::Command` work, and made that function swallow errors rather than return them or panic (because we want to keep systemd optional)
- pass a null stdin to `std::process::Command`, because it's allegedly faster to skip inheriting the parent's stdin (and it's not our intention to allow this inheritance anyway)
- switch from `.spawn()` to `.status()` so that we can at least find out if `systemctl` accepted our calls (mostly for diagnostic purposes)
- pass `--no-block` to `systemctl` when starting/stopping the graphical target, because we care mostly that we called into systemd successfully, not what happens inside systemd after that
in all testing below, the session and compositor continue to launch as normal:
- tested the happy path, and that `systemctl …
> fix: allow calls for systemd graphical target to fail

- src/main.rs
- src/systemd.rs
~- hardcode XDG_SESSION_TYPE=wayland, because otherwise it defaults to tty on my system, which means the "about" page in cosmic-settings says "tty" instead of "wayland" (and COSMIC doesn't need to support/advertise any other value other than wayland)~
~- hardcode XDG_CURRENT_DESKTOP=cosmic, to improve the integration with xdg-desktop-portal and xdg-desktop-portal-cosmic (one step towards allowing `xdg-desktop-portal` to start `xdg-desktop-portal-cosmic` on-demand rather than explicitly starting it here in `cosmic-session`)~
~- modify `start-cosmic` so that it checks for `systemctl` before calling it (helping to make systemd optional)~
- per https://github.com/pop-os/cosmic-session/pull/31#issuecomment-1883016009
- re-order start sequence so that systemd is notified that we've reached …
> feat: set XDG_DESKTOP_TYPE=wayland after cosmic-comp is ready and just before graphical-session.target

- Cargo.lock
- Cargo.toml
- src/service.rs
updated zbus to use the proxy attribute macro. It seemed to be missing on version 3.4
> updated zbus to 4.3

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/systemd.rs
- Depends on #53 
- Depends on [lauch-pad#12](https://github.com/pop-os/launch-pad/pull/12)
- Related to [cosmic-epoch#356](https://github.com/pop-os/cosmic-epoch/issues/356)
Still a draft, open to making any changes or taking an alternative approach. This adds a function for checking whether systemd is the init system ( I need to confirm the path linked is correct for all distros), and uses zbus to start a transient service for each process. 
I need to test this locally, and I want to implement a few other relevant methods from systemd. 
A relevant crate that might be worth considering as a dependency is [zbus_systemd](https://docs.rs/zbus_systemd). I wasn't if their version of start_transient_unit allowed for setting the PIDs property, and didn't want to add a dependency without asking …
> Attach launched processes to systemd scopes

- Cargo.toml
- src/main.rs
Addresses: https://github.com/pop-os/cosmic-session/issues/51
Currently trying to build without the `systemd` feature causes compile time errors. The first commit in this PR simply fixes those.
The seconds commit turns `tracing-journald` into an optional dependency which is only included when building with the `systemd` feature.
The third commit removes the runtime panic that occurs when  `journald` is not available on a system, falling back to a default and providing a warning instead of a hard crash. This is useful on distros like Artix or Devuan where many features of systemd are available (dbus, logind), such that building with the `systemd` feature is preferable, but journald is not present.
> Fix building and running on systems without systemd

- data/start-cosmic
This makes sure together with our XSettings implementation in cosmic-comp, that QT apps running on their xcb backend will react to the DPI values we are setting by changing their internal scaling.
~~Depends on https://github.com/pop-os/cosmic-comp/pull/779 being merged first.~~ cosmic-comp changes merged.
> start-cosmic: Set QT auto scaling env variables

- debian/control
- src/main.rs
https://github.com/pop-os/cosmic-settings/pull/704 should be merged first, to have a way to control this.
We may also want to change the defaults in https://github.com/pop-os/cosmic-idle/blob/master/cosmic-idle-config/src/lib.rs before making it start by default.
> Launch `cosmic-idle`

- src/comp.rs
- src/main.rs
This allows alternative compositors to be used in a cosmic-like session. Other ways to provide the compositor<->session api may be provided by external projects.
> Allow alternative sessions

- data/dconf/profile/cosmic
- data/start-cosmic
- debian/cosmic-session.install
This causes the cosmic-session to have a separate writable dconf-database (while still inheriting the default user database).
This will (partially) prevent issues such as https://github.com/pop-os/cosmic-epoch/issues/1174 in the future, as other desktops won't pick up cosmic's dconf profile.
**Note to packagers**: The dconf profile is highly specific to POP!_OS, which it why it isn't picked up by our `Justfile`. You are highly encouraged to provide your own.
Pop!_OS doesn't have a default user-profile, which means the profile defaults to `user-db:user` (see [man 7 dconf](https://man.archlinux.org/man/dconf.7.en#PROFILES)). The contents of the cosmic profile should be:
```
user-db:cosmic
[the contents of /usr/share/dconf/profile/user of your distro]
```
Failing to provide a cosmic profile …
> session: Add custom dconf profile

- Justfile
Addresses the problem pointed out here: https://github.com/pop-os/cosmic-session/pull/90#issuecomment-2521418496
Apparently dconf doesn't by default lookup `/usr/share/` and just `/etc/`. This oversight causes our session on Pop!_OS to now have a read-only profile...
Given other distributions might run into similar problems, if they don't want to install the profile to `/etc`, I also made it configurable at install time.
> build: Make dconf profile path explicit and configurable

- data/start-cosmic
Lets see if this fixes gsettings sync into flatpaks.
(Presumably the gtk-portal didn't get the memo of our custom dconf profile otherwise.)
> start-cosmic: Import DCONF_PROFILE into systemd user environment

- Justfile
This wasn't being installed by the justfile, so distros using the
justfile for packaging weren't properly installing the dconf profile.
Fixes https://gitlab.alpinelinux.org/alpine/aports/-/issues/17056
> Install dconf profile

- src/main.rs
Resolves #93.
Related: #83.
This PR is based on [this comment](https://github.com/pop-os/cosmic-session/issues/83#issuecomment-2823798796). It simply changes the behavior when fail to launch service from panic to just logging to the stderr.
> fix: ignore error when starting service

- .rustfmt.toml
- Cargo.lock
- Cargo.toml
- src/comp.rs
- src/main.rs
- src/notifications.rs
- src/systemd.rs
Removes the use of `set_var`, since it isn't thread safe. It didn't even want to compile with that for me, so not sure how it did so far.
Removes some unnecessary/obsolete options in `rustfmt.toml`.
Haven't noticed any issues with the changes from some light testing.
> Migrate to Rust 2024 and update dependencies
